apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: argocd/catalog-ms/config
    repoURL: "https://github.com/sibabalwe47/e-commerce.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - createNamespace=true

