name: Authentication microservice pipeline.
on:
  push:
    branches: [main]

env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}


jobs:
  catalog_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

    - name: Build the Docker image # push The image to the docker hub
      run: |

        echo ${{ github.workspace }}
        cd ${{ github.workspace }} && ls
        docker build  --t $DOCKER_USER/catalog:${{ steps.date.outputs.date }} ${{ github.workspace }}/backend/catalog-ms
    - name: Docker Push
      run: |
        docker push $DOCKER_USER/catalog:${{ steps.date.outputs.date }}


